version: '3.8'

services:
  main-db:
    image: mysql
    restart: always
    container_name: thon-labs-main-db
    environment:
      MYSQL_DATABASE: 'thon-labs'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/db:/var/lib/mysql
