version: '3.8'

services:
  main-db:
    image: postgres
    restart: always
    container_name: thonlabs-main-db
    environment:
      POSTGRES_DB: 'thonlabs'
      POSTGRES_USER: 'thonlabs'
      POSTGRES_PASSWORD: '12345678'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
